deployment:
  tasks:
    - export DEPLOYPATH=/home/flawhvna/public_html/

    - /usr/bin/rsync -av --delete \
      --exclude='.git' \
      --exclude='.cpanel.yml' \
      --exclude='.github' \
      ./ $DEPLOYPATH