---
deployment:
  tasks:
    - export DEPLOYPATH=/home/flawhvna/public_html/
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/mkdir -p $DEPLOYPATH/blog
    - /bin/mkdir -p $DEPLOYPATH/fwitter
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp maintenance-page.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R blog/* $DEPLOYPATH/blog/
    - /bin/cp -R fwitter/* $DEPLOYPATH/fwitter/
    - /bin/cp api/micro-posts.php $DEPLOYPATH/api/micro-posts.php
    - /bin/cp api/github-last-commit.php $DEPLOYPATH/api/github-last-commit.php
    - /bin/cp api/health-common.php $DEPLOYPATH/api/health-common.php
    - /bin/cp api/health-auth.php $DEPLOYPATH/api/health-auth.php
    - /bin/cp api/health-metrics.php $DEPLOYPATH/api/health-metrics.php
