---
deployment:
  tasks:
    - export DEPLOYPATH=/home/flawhvna/public_html/
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp maintenance-page.html $DEPLOYPATH
    - /bin/cp api/micro-posts.php $DEPLOYPATH/api/micro-posts.php
    - /bin/cp api/github-last-commit.php $DEPLOYPATH/api/github-last-commit.php
